---
# Генерация файлов виртуальных хостов apache для БД
- name: Generate apache vhosts files
  template:
    src: "apache-vhosts.conf.j2"
    dest: "/etc/httpd/conf.d/{{ item.key }}.conf"
  loop: "{{ lookup('dict', databses) }}"
  notify: restart apache
