---
# tasks file for apache-1c
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install tasks.
- include_tasks: "download-onec-distr.yml"
- include_tasks: "setup-{{ ansible_os_family }}.yml"
- include_tasks: "configure-onec-webapp.yml"
- include_tasks: "configure-{{ ansible_os_family }}.yml"

# Enable startup on boot and start Apache.
- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "started"
    enabled: true
