---
- name: Converge
  vars_files:
    - vars/common_vars.yml
  hosts: all
  vars:
    is_travis: "{{ lookup('env','TRAVIS') }}"
  pre_tasks:
    - name: Include vars
      include_vars: "vars/ci_vars.yml"
      when: is_travis

    - name: Include vars
      include_vars: "vars/local_vars.yml"
      when: not is_travis
  roles:
    - role: bessonovevgen.apache-1c
